# Generated by Django 4.2.16 on 2024-09-15 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255, verbose_name='Наименование'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=255, unique=True, verbose_name='slug-имя'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=products.models.get_upload_to,
                        verbose_name='Изображение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255, verbose_name='Наименование'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=255, unique=True, verbose_name='slug-имя'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=products.models.get_upload_to,
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subcategories',
                        to='products.category',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'подкатегорию',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255, verbose_name='Наименование'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=255, unique=True, verbose_name='slug-имя'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=products.models.get_upload_to,
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='Цена',
                    ),
                ),
                (
                    'subcategory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='products.subcategory',
                        verbose_name='Подкатегория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
