# Generated by Django 4.2.16 on 2024-09-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ('id',),
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
