# Generated by Django 4.2.16 on 2024-09-17 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество",
            ),
        ),
    ]
